### ISSUE TITLE
request: dynamic (on-the-fly) change background color

### ISSUE THREAD

**Issue by stewie** [zden/face.haluska.sk#3]
As is, must "Start With" a chosen bgcolor. It would be much more interesting to experiment with changing bgcolor (of the canvas element, via css) while the drawing progresses.

Separately, it would be interesting if the scaled (to match canvas dimensions) source image was viewable real-time (without pausing the drawing). The source image could be displayed to a higher z-index element, with a toggle (better: an opacity slider) to control its visibility. 

If, instead of displaying the source image to an img element, the source image was rendered to a separate canvas context, the controls could include a selector enabling the user to toggle globalCompositeOperation modes...

**Comment by zden** [comment]
Hello Stewie. In recent version it's done as you proposed.
Background color is tweakable during the paint process and can be altered at any time.
Even the bitmap will be saved as transparent.
